---
- name: Test CRI-O cri
  import_playbook: ../../../molecule/test_cri.yml
  vars:
    container_manager: crio
    cri_socket: unix:///var/run/crio/crio.sock
    cri_name: cri-o
- name: Test running a container with crun
  import_playbook: ../../../molecule/test_runtime.yml
  vars:
    container_runtime: crun
